package com.in28minutes.rest.webservices.restfulwebservices.todo;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
public class TodoJpaResource {

    private final TodoService todoService;
    private final TodoRepository todoRepository;

    public TodoJpaResource(TodoService todoService, TodoRepository todoRepository) {
        this.todoService = todoService;
        this.todoRepository = todoRepository;
    }

    @GetMapping("/users/{username}/todos")
    public List<Todo> retrieveAllTodos(@PathVariable String username) {
        return todoRepository.findByUsername(username);
    }

    @GetMapping("/users/{username}/todos/{id}")
    public Todo retrieveTodoById(@PathVariable String username, @PathVariable int id) {
        return todoRepository.findById(id).get();
    }


    @DeleteMapping("/users/{username}/todos/{id}")
    public ResponseEntity<Void> deleteTodoById(@PathVariable String username, @PathVariable int id) {
        todoRepository.deleteById(id);
        return ResponseEntity.noContent().build();
    }

    @PutMapping("/users/{username}/todos/{id}")
    public Todo updateTodoById(@PathVariable String username, @PathVariable int id, @RequestBody Todo todo) {
        Todo todoToUpdate = todoRepository.getReferenceById(id);
        todoToUpdate.setDescription(todo.getDescription());
        todoToUpdate.setTargetDate(todo.getTargetDate());
        todoRepository.save(todoToUpdate);
        return todo;
    }

    @PostMapping("/users/{username}/todos")
    public Todo createTodo(@PathVariable String username, @RequestBody Todo todo) {
        // Set the username to the username passed in the path
        todo.setUsername(username);
        // Set the id to null so that it is created as a new record instead of updating an existing record
        // This is because the id is auto-generated by the database
        // Id should be Integer instead of int so that it can be set to null
        todo.setId(null);
        return todoRepository.save(todo);
    }
}
