INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (10001, 'Learn Spring MVC', false, CURRENT_DATE(), 'in28minutes');

INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (10002, 'Learn Spring JPA', false, CURRENT_DATE(), 'in28minutes');

INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (10003, 'Learn Spring Security', false, CURRENT_DATE(), 'in28minutes');
